// iconMap.js
import {
    FireOutlined,
    CheckCircleOutlined,
    CloseCircleOutlined,
    ClockCircleOutlined,
    ThunderboltOutlined,
    FlagOutlined,
    SmileOutlined,
    FrownOutlined,
    HeartOutlined,
    AimOutlined,
    TrophyOutlined,
    StepBackwardOutlined,
    StepForwardOutlined,
    UserOutlined,
    EnvironmentOutlined,
    BarChartOutlined,
    DashboardOutlined,
    MedicineBoxOutlined,
    HistoryOutlined,
    ExperimentOutlined,
    AreaChartOutlined,
    PieChartOutlined,
    LineChartOutlined,
    WarningOutlined,
  } from '@ant-design/icons';
  
  const iconMap = {
    "FireOutlined": FireOutlined,
    "CheckCircleOutlined": CheckCircleOutlined,
    "CloseCircleOutlined": CloseCircleOutlined,
    "ClockCircleOutlined": ClockCircleOutlined,
    "ThunderboltOutlined": ThunderboltOutlined,
    "FlagOutlined": FlagOutlined,
    "SmileOutlined": SmileOutlined,
    "FrownOutlined": FrownOutlined,
    "HeartOutlined": HeartOutlined,
    "AimOutlined": AimOutlined,
    "TrophyOutlined": TrophyOutlined,
    "StepBackwardOutlined": StepBackwardOutlined,
    "StepForwardOutlined": StepForwardOutlined,
    "UserOutlined": UserOutlined,
    "EnvironmentOutlined": EnvironmentOutlined,
    "BarChartOutlined": BarChartOutlined,
    "DashboardOutlined": DashboardOutlined,
    "MedicineBoxOutlined": MedicineBoxOutlined,
    "HistoryOutlined": HistoryOutlined,
    "ExperimentOutlined": ExperimentOutlined,
    "AreaChartOutlined": AreaChartOutlined,
    "PieChartOutlined": PieChartOutlined,
    "LineChartOutlined": LineChartOutlined,
    "WarningOutlined": WarningOutlined,
  };
  
  export default iconMap;
  