/**
 * backend/configs/openAiSystemConfigs.js
 *
 * Domain-rich OpenAI-facing config for the hybrid Fitbit QnA pipeline.
 *
 * Goals:
 * - keep the new schema-driven architecture
 * - restore the old system's domain richness and flexibility
 * - keep calculations deterministic and backend-owned
 * - keep spoken response + visual tightly paired
 * - support progressive drill-downs for older-adult-friendly interaction
 */

const VISUAL_SYSTEM = {
  app: {
    voiceMaxWords: 65,
    voiceMaxChars: 420,
    defaultTimeScope: "last_7_days",
    supportedTimeScopes: [
      "today",
      "yesterday",
      "last_night",
      "this_week",
      "last_week",
      "last_7_days",
      "last_30_days",
    ],
  },

  voice: {
    maxWords: 65,
    maxChars: 420,
    maxSentences: 4,
  },

  allowed: {
    questionTypes: [
      "overview_report",
      "comparison_report",
      "single_metric_status",
      "relationship_report",
      "anomaly_explanation",
      "goal_progress",
      "chart_explanation",
      "deep_dive",
      "reminder",
      "unsupported",
    ],
    metrics: [
      "steps",
      "distance",
      "floors",
      "elevation",
      "calories",
      "sleep_minutes",
      "sleep_efficiency",
      "wake_minutes",
      "breathing_rate",
      "spo2",
      "weight",
      "body_fat",
      "resting_hr",
      "heart_intraday",
      "steps_intraday",
      "calories_intraday",
      "distance_intraday",
      "floors_intraday",
      "hrv",
    ],
    comparisonModes: ["none", "previous_period", "metric_vs_metric"],
    responseModes: ["single_view", "multi_panel_report"],
    layouts: [
      "single_focus",
      "two_up",
      "two_up_plus_footer",
      "three_panel_report",
      "four_panel_grid",
    ],
    reportGoals: [
      "overview_report",
      "comparison_report",
      "single_metric_status",
      "relationship_report",
      "anomaly_explanation",
      "goal_progress",
      "chart_explanation",
      "deep_dive",
    ],
    evidenceScopes: [
      "sleep_core",
      "sleep_timing_and_stages",
      "activity_core",
      "daily_activity_breakdown",
      "heart_recovery",
      "relationship_bundle",
      "weekly_anomaly_scan",
      "screen_context_expansion",
    ],
    followupModes: ["none", "suggested_drill_down", "chart_aware", "free_form"],
    chartTypes: [
      "bar",
      "grouped_bar",
      "line",
      "multi_line",
      "stacked_bar",
      "scatter",
      "area",
      "heatmap",
      "radar",
      "boxplot",
      "timeline",
      "gauge",
      "list_summary",
      "pie",
      "composed_summary",
    ],
  },

  proxyMap: {
    energy: "steps",
    tired: "sleep_minutes",
    tiredness: "sleep_minutes",
    fatigue: "sleep_minutes",
    breathing: "breathing_rate",
    respiratory: "breathing_rate",
    oxygen: "spo2",
    spo2: "spo2",
    recovery: "hrv",
    stress: "hrv",
    exercise: "calories",
    workout: "calories",
    activity: "steps",
    movement: "steps",
    walking: "steps",
    cardio: "resting_hr",
    heart: "resting_hr",
    sleep: "sleep_minutes",
  },

  metricAliases: {
    heart: "resting_hr",
    pulse: "resting_hr",
    bpm: "resting_hr",
    stress: "hrv",
    variability: "hrv",
    recovery: "hrv",
    breathing: "breathing_rate",
    respiratory: "breathing_rate",
    oxygen: "spo2",
    spo2: "spo2",
    saturation: "spo2",
    weight: "weight",
    bmi: "weight",
    fat: "body_fat",
    bodyfat: "body_fat",
    sleep: "sleep_minutes",
    resting: "resting_hr",
    walking: "steps",
    move: "steps",
    moved: "steps",
    stairs: "floors",
    climbed: "floors",
    burned: "calories",
  },

  timeScopeConfig: {
    today: { baseDays: 1, label: "today", offsetDays: 0 },
    yesterday: { baseDays: 1, label: "yesterday", offsetDays: 1 },
    last_night: { baseDays: 1, label: "last night", offsetDays: 1 },
    this_week: { baseDays: 7, label: "this week", offsetDays: 0 },
    last_week: { baseDays: 7, label: "last week", offsetDays: 7 },
    last_7_days: { baseDays: 7, label: "last 7 days", offsetDays: 0 },
    last_30_days: { baseDays: 30, label: "last 30 days", offsetDays: 0 },
  },

  chartDefaults: {
    axisFontSize: 14,
    labelFontSize: 14,
    titleFontSize: 18,
    subtitleFontSize: 14,
    barRadius: 10,
    lineWidth: 4,
    gaugeFontSize: 40,
  },

  palettes: {
    steps: {
      primary: "#0EA5E9",
      secondary: "#14B8A6",
      accent: "#F59E0B",
      background: "#F0F9FF",
      text: "#0F172A",
      series: ["#0EA5E9", "#14B8A6", "#F59E0B", "#8B5CF6", "#EF4444", "#22C55E"],
    },
    distance: {
      primary: "#14B8A6",
      secondary: "#0EA5E9",
      accent: "#F59E0B",
      background: "#ECFDF5",
      text: "#0F172A",
      series: ["#14B8A6", "#0EA5E9", "#F59E0B", "#8B5CF6"],
    },
    floors: {
      primary: "#F59E0B",
      secondary: "#F97316",
      accent: "#0EA5E9",
      background: "#FFFBEB",
      text: "#0F172A",
      series: ["#F59E0B", "#F97316", "#0EA5E9", "#8B5CF6"],
    },
    elevation: {
      primary: "#84CC16",
      secondary: "#14B8A6",
      accent: "#F59E0B",
      background: "#F7FEE7",
      text: "#0F172A",
      series: ["#84CC16", "#14B8A6", "#F59E0B", "#0EA5E9"],
    },
    calories: {
      primary: "#F97316",
      secondary: "#F59E0B",
      accent: "#E11D48",
      background: "#FFF7ED",
      text: "#0F172A",
      series: ["#F97316", "#F59E0B", "#E11D48", "#0EA5E9", "#8B5CF6"],
    },
    sleep_minutes: {
      primary: "#5B6CFF",
      secondary: "#8B5CF6",
      accent: "#2DD4BF",
      background: "#EEF2FF",
      text: "#0F172A",
      series: ["#5B6CFF", "#8B5CF6", "#2DD4BF", "#F59E0B", "#06B6D4"],
    },
    sleep_efficiency: {
      primary: "#6366F1",
      secondary: "#8B5CF6",
      accent: "#2DD4BF",
      background: "#EEF2FF",
      text: "#0F172A",
      series: ["#6366F1", "#8B5CF6", "#2DD4BF", "#F59E0B"],
    },
    wake_minutes: {
      primary: "#FB7185",
      secondary: "#F43F5E",
      accent: "#F59E0B",
      background: "#FFF1F2",
      text: "#0F172A",
      series: ["#FB7185", "#F43F5E", "#F59E0B", "#8B5CF6"],
    },
    breathing_rate: {
      primary: "#0F766E",
      secondary: "#14B8A6",
      accent: "#5EEAD4",
      background: "#F0FDFA",
      text: "#0F172A",
      series: ["#0F766E", "#14B8A6", "#5EEAD4", "#0EA5E9"],
    },
    spo2: {
      primary: "#0284C7",
      secondary: "#38BDF8",
      accent: "#7DD3FC",
      background: "#F0F9FF",
      text: "#0F172A",
      series: ["#0284C7", "#38BDF8", "#7DD3FC", "#14B8A6"],
    },
    weight: {
      primary: "#9333EA",
      secondary: "#A855F7",
      accent: "#D8B4FE",
      background: "#FAF5FF",
      text: "#0F172A",
      series: ["#9333EA", "#A855F7", "#D8B4FE", "#F59E0B"],
    },
    body_fat: {
      primary: "#C2410C",
      secondary: "#EA580C",
      accent: "#FB923C",
      background: "#FFF7ED",
      text: "#0F172A",
      series: ["#C2410C", "#EA580C", "#FB923C", "#F59E0B"],
    },
    resting_hr: {
      primary: "#E11D48",
      secondary: "#FB7185",
      accent: "#F59E0B",
      background: "#FFF1F2",
      text: "#0F172A",
      series: ["#E11D48", "#FB7185", "#F59E0B", "#06B6D4", "#8B5CF6"],
    },
    heart_intraday: {
      primary: "#DC2626",
      secondary: "#FB7185",
      accent: "#F59E0B",
      background: "#FEF2F2",
      text: "#0F172A",
      series: ["#DC2626", "#FB7185", "#F59E0B", "#8B5CF6"],
    },
    steps_intraday: {
      primary: "#0284C7",
      secondary: "#14B8A6",
      accent: "#F59E0B",
      background: "#F0F9FF",
      text: "#0F172A",
      series: ["#0284C7", "#14B8A6", "#F59E0B", "#8B5CF6"],
    },
    calories_intraday: {
      primary: "#EA580C",
      secondary: "#F59E0B",
      accent: "#E11D48",
      background: "#FFF7ED",
      text: "#0F172A",
      series: ["#EA580C", "#F59E0B", "#E11D48", "#0EA5E9"],
    },
    distance_intraday: {
      primary: "#0D9488",
      secondary: "#0EA5E9",
      accent: "#F59E0B",
      background: "#F0FDFA",
      text: "#0F172A",
      series: ["#0D9488", "#0EA5E9", "#F59E0B", "#8B5CF6"],
    },
    floors_intraday: {
      primary: "#D97706",
      secondary: "#F97316",
      accent: "#0EA5E9",
      background: "#FFFBEB",
      text: "#0F172A",
      series: ["#D97706", "#F97316", "#0EA5E9", "#8B5CF6"],
    },
    hrv: {
      primary: "#8B5CF6",
      secondary: "#14B8A6",
      accent: "#F59E0B",
      background: "#F5F3FF",
      text: "#0F172A",
      series: ["#8B5CF6", "#14B8A6", "#5B6CFF", "#F59E0B", "#06B6D4"],
    },
    relationship: {
      primary: "#5B6CFF",
      secondary: "#14B8A6",
      accent: "#F59E0B",
      background: "#EEF2FF",
      text: "#0F172A",
      series: ["#5B6CFF", "#14B8A6", "#F59E0B", "#EF4444", "#8B5CF6", "#06B6D4"],
    },
    fallback: {
      primary: "#2563EB",
      secondary: "#14B8A6",
      accent: "#F59E0B",
      background: "#EFF6FF",
      text: "#0F172A",
      series: ["#2563EB", "#14B8A6", "#F59E0B", "#8B5CF6", "#EF4444", "#06B6D4"],
    },
  },
};

function metricToPalette(metricKey) {
  return VISUAL_SYSTEM.palettes[metricKey] || VISUAL_SYSTEM.palettes.fallback;
}

const FETCH_PLAN_SCHEMA = {
  name: "fitbit_qna_plan",
  schema: {
    type: "object",
    additionalProperties: false,
    properties: {
      question_type: { type: "string", enum: VISUAL_SYSTEM.allowed.questionTypes },
      response_mode: { type: "string", enum: VISUAL_SYSTEM.allowed.responseModes },
      metrics_needed: {
        type: "array",
        minItems: 1,
        maxItems: 4,
        items: { type: "string", enum: VISUAL_SYSTEM.allowed.metrics },
      },
      time_scope: { type: "string", enum: VISUAL_SYSTEM.app.supportedTimeScopes },
      comparison_mode: { type: "string", enum: VISUAL_SYSTEM.allowed.comparisonModes },
      needs_previous_period: { type: "boolean" },
      needs_intraday: { type: "boolean" },
      evidence_scope: {
        type: "array",
        minItems: 1,
        maxItems: 4,
        items: { type: "string", enum: VISUAL_SYSTEM.allowed.evidenceScopes },
      },
      needs_relationship_scan: { type: "boolean" },
      needs_goal_context: { type: "boolean" },
      needs_screen_context: { type: "boolean" },
      followup_mode: { type: "string", enum: VISUAL_SYSTEM.allowed.followupModes },
      preferred_chart: { type: "string", enum: VISUAL_SYSTEM.allowed.chartTypes },
      visual_goals: {
        type: "array",
        minItems: 1,
        maxItems: 4,
        items: { type: "string", enum: VISUAL_SYSTEM.allowed.reportGoals },
      },
      layout_hint: { type: "string", enum: VISUAL_SYSTEM.allowed.layouts },
      drill_down_candidates: {
        type: "array",
        minItems: 0,
        maxItems: 4,
        items: { type: "string" },
      },
    },
    required: [
      "question_type",
      "response_mode",
      "metrics_needed",
      "time_scope",
      "comparison_mode",
      "needs_previous_period",
      "needs_intraday",
      "evidence_scope",
      "needs_relationship_scan",
      "needs_goal_context",
      "needs_screen_context",
      "followup_mode",
      "preferred_chart",
      "visual_goals",
      "layout_hint",
      "drill_down_candidates",
    ],
  },
};

const PRESENTATION_SCHEMA = {
  name: "fitbit_qna_present",
  schema: {
    type: "object",
    additionalProperties: false,
    properties: {
      response_mode: { type: "string", enum: VISUAL_SYSTEM.allowed.responseModes },
      layout: { type: "string", enum: VISUAL_SYSTEM.allowed.layouts },
      spoken_answer: { type: "string" },
      report_title: { type: "string" },
      takeaway: { type: "string" },
      panels: {
        type: "array",
        minItems: 1,
        maxItems: 4,
        items: {
          type: "object",
          additionalProperties: false,
          properties: {
            panel_id: { type: "string" },
            goal: { type: "string", enum: VISUAL_SYSTEM.allowed.reportGoals },
            metrics: {
              type: "array",
              minItems: 1,
              maxItems: 4,
              items: { type: "string", enum: VISUAL_SYSTEM.allowed.metrics },
            },
            visual_family: { type: "string", enum: VISUAL_SYSTEM.allowed.chartTypes },
            title: { type: "string" },
            subtitle: { type: "string" },
            emphasis: { type: "string", enum: ["hero", "standard"] },
          },
          required: ["panel_id", "goal", "metrics", "visual_family", "title", "subtitle"],
        },
      },
      next_views: {
        type: "array",
        minItems: 0,
        maxItems: 4,
        items: {
          type: "object",
          additionalProperties: false,
          properties: {
            id: { type: "string" },
            label: { type: "string" },
            goal: { type: "string", enum: VISUAL_SYSTEM.allowed.reportGoals },
            metrics: {
              type: "array",
              minItems: 1,
              maxItems: 4,
              items: { type: "string", enum: VISUAL_SYSTEM.allowed.metrics },
            },
          },
          required: ["id", "label", "goal", "metrics"],
        },
      },
      suggested_followup_prompt: { type: "string" },
      followup_mode: { type: "string", enum: VISUAL_SYSTEM.allowed.followupModes },
    },
    required: [
      "response_mode",
      "layout",
      "spoken_answer",
      "report_title",
      "takeaway",
      "panels",
      "next_views",
      "suggested_followup_prompt",
      "followup_mode",
    ],
  },
};

const FOLLOWUP_SCHEMA = {
  name: "fitbit_followup_response",
  schema: {
    type: "object",
    additionalProperties: false,
    properties: {
      answer: { type: "string" },
      suggestedQuestions: {
        type: "array",
        minItems: 1,
        maxItems: 4,
        items: { type: "string" },
      },
    },
    required: ["answer", "suggestedQuestions"],
  },
};

const HEALTH_INTERPRETATION_PLAYBOOK = [
  "You are planning and explaining Fitbit-based health questions for a smart screen and Alexa experience used by older adults.",
  "The novelty is not raw plotting. The novelty is selecting the right evidence bundle, surfacing patterns, comparisons, anomalies, and relationships, and then pairing that inference with one clear visual or one coordinated report.",
  "Use broad but safe health context when explaining meaning, but do not diagnose, prescribe medication, or claim certainty beyond the provided data.",
  "Prefer clear insight over exhaustive detail. Use a single focused visual for narrow questions and a coordinated report for broader questions.",
  "If the user asks a broad question like overview, report, how am I doing, what should I know, or anything similar, do not ask them to narrow it down. Choose the most informative metric bundle and proceed.",
  "If the user asks for more detail, more explanation, continue, or why, prefer chart-aware continuation instead of re-asking the same question.",
  "Do not give shallow answers that simply repeat raw averages. Highlight what changed, what was unusual, how metrics relate, and what the user should learn from the pattern.",
  "When the user asks about sleep, stage balance, wake periods, timing, efficiency, and sleep continuity often matter more than total minutes alone.",
  "When the user asks about activity for a single day, exercise logs, active minutes, heart zones, calories, and goal context are often more meaningful than just one daily total.",
  "Treat the screen as a visual blackboard for the explanation. The voice answer should be short, but the selected visuals should carry the evidence behind the explanation.",
].join(" ");

const DOMAIN_REASONING_GUIDE = [
  "Sleep questions often need sleep_minutes, and when the user asks about quality, restfulness, stages, timing, wake-ups, or what happened last night, also use sleep_timing_and_stages.",
  "Activity questions often map to steps, calories, distance, floors, or elevation. Movement, walking, active, sedentary, and exercise usually imply activity_core.",
  "Breathing rate and blood oxygen questions are sleep-recovery signals. If the user asks about breathing, respiratory rate, blood oxygen, oxygen saturation, or SpO2, include those metrics directly.",
  "Body questions may involve weight, BMI, or body fat. If the user asks about weight change, body composition, or body fat, include the body metrics instead of defaulting to activity.",
  "Intraday questions include today by hour, morning, afternoon, evening, spike, dip, when, timeline, around lunch, before bed, and what happened during the day. Those should favor daily_activity_breakdown or heart_intraday depending on the metric.",
  "Heart and recovery questions may involve resting_hr, heart_intraday, and hrv. Use heart_recovery when recovery, stress, readiness, or heart strain is implied.",
  "Relationship questions ask how one factor relates to another, such as sleep vs steps, sleep vs heart rate, or activity vs recovery. Use relationship_bundle and metric_vs_metric.",
  "Comparison questions include compared with, versus, relative to, better than, worse than, has it changed, trend, and since last week. Those usually need previous_period or metric_vs_metric.",
  "Anomaly and consistency questions include unusual, off, irregular, pattern, steady, consistent, variable, spike, dip, and stand out. Those often need weekly_anomaly_scan.",
  "Explain_chart questions include what am I looking at, explain this chart, what does this mean, what stands out here, or explain the graph. Those should use screen_context_expansion and keep the explanation visual-aware.",
  "For single-day sleep questions, favor the single-day sleep detail endpoint so stage timeline, latency, wake periods, and efficiency are available.",
  "For single-day activity questions, include the daily activity summary endpoint so logged exercise, active minutes, heart zones, calorie totals, resting heart rate, and goals can inform the answer.",
  "If sleep detail is available, a timeline or stage-oriented view is usually more informative than a plain duration bar.",
].join(" ");

const FETCH_PLANNER_CONFIG = {
  model: process.env.OPENAI_QNA_MODEL || "gpt-4o-mini",
  temperature: 0.12,
  maxTokens: null,
  timeoutMs: null,
  jsonSchema: FETCH_PLAN_SCHEMA,
  systemPrompt: [
    "You are the GPT-first retrieval planner for a Fitbit health QnA app. Plan from the user question and the allowed enums only; no other plan is provided.",
    HEALTH_INTERPRETATION_PLAYBOOK,
    DOMAIN_REASONING_GUIDE,
    "Return strict JSON only and follow the schema exactly.",
    "Do not write prose analysis. Your job is to infer the user intent and plan backend retrieval plus report intent.",
    "Think through all relevant metrics that could be displayed for this question. For sleep, include sleep_minutes, sleep_efficiency, wake_minutes, breathing_rate, spo2, evidence_scope, sleep_timing_and_stages so stage and overnight recovery detail is available. For activity include steps, calories, or distance as relevant; for heart include resting_hr or hrv; for body questions include weight or body_fat. For overview or report-style questions include at least 3–4 metrics from different domains (e.g. sleep, activity, heart, body) so the report is informative.",
    "For sleep, activity or heart related questions make sure to get trends over time",
    "Be flexible with natural language. Infer what the user means even when they do not name the Fitbit metric directly.",
    "Use the minimum evidence bundle that still supports a smart answer. Do not ask for every metric unless the user truly asked for an overview or report.",
    "For overview questions (overview_report or broad how am I doing / report requests), include at least 3 metrics so the report is informative.",
    "When sleep is mentioned, always include evidence_scope sleep_timing_and_stages so stage and timing detail is available. When including sleep_minutes, also include sleep_efficiency and wake_minutes so efficiency and wake data are available. Include breathing_rate and spo2 when the wording suggests overnight breathing or oxygen quality.",
    "For vague but meaningful questions, avoid unsupported unless the question is truly outside the health-data domain.",
    "Question type guidance: overview_report = broad multi-metric summary; comparison_report = explicit or implicit prior-period comparison; single_metric_status = current state of one metric; relationship_report = how two factors move together; anomaly_explanation = explain a spike, dip, or unusual pattern; goal_progress = progress toward a target; chart_explanation = explain what is shown on screen; deep_dive = requested drill-down or more detail; reminder = reminder-related requests; unsupported = clearly outside supported scope.",
    "Time scope guidance: today for same-day intraday or same-day status; yesterday or last_night for recent sleep or previous-day questions; this_week or last_week for week framing; last_7_days as the default trend window; last_30_days for longer trend requests.",
    "Response guidance: choose single_view for narrow or explanation-focused questions and multi_panel_report for overview, broad comparison, or relationship questions.",
    "Set needs_previous_period when the answer depends on comparing against an earlier period. Set needs_intraday when within-day data is required.",
    "For single-day questions, prefer needs_intraday when the metric supports intraday data. For single-day sleep detail, make sure sleep timing and stage evidence is included.",
    "Chart guidance: visual_goals describe the story each panel should tell. Use timeline or area for intraday patterns, scatter for relationships, grouped_bar for prior-period comparison, gauge for goal progress, pie for sleep stage composition, composed_summary for broad overviews, multi_line for multiple daily metrics, and simple bar or line when clarity matters most.",
    "Follow-up guidance: suggested_drill_down when a natural next question exists; chart_aware when the likely next step is to explain or zoom further into the shown visual; free_form only when the user is already in an open conversational follow-up; none when the answer should stand alone.",
    "For older-adult-friendly interaction, prefer a single focused chart for narrow questions and a coordinated report of at most four panels for broad ones.",
  ].join(" "),
};

const PRESENT_CONFIG = {
  model: process.env.OPENAI_QNA_MODEL || "gpt-4o-mini",
  temperature: 0.28,
  maxTokens: null,
  timeoutMs: null,
  jsonSchema: PRESENTATION_SCHEMA,
  systemPrompt: [
    "You are the presentation planner for a health-data smart screen and Alexa experience.",
    HEALTH_INTERPRETATION_PLAYBOOK,
    "You are speaking to an older adult. Be calm, plain-English, supportive, and informative.",
    "Use only the deterministic facts that are provided. Never invent, estimate, or round beyond what is already computed.",
    "Your goal is not to recite raw numbers. Your goal is to convert computed facts into a short, understandable explanation of what matters, why it matters, and what the user may want to see next.",
    "When relevant, add light general-health context such as why sleep regularity matters, why resting heart rate trends matter, why consistency matters, or why stage balance is worth noticing. Keep that context broad and non-diagnostic.",
    "Make the spoken response meaningful: two to four sentences that cover the headline finding and one or two supporting details. It should be rich enough that a listener learns something, not just a single number.",
    "Choose response_mode, layout, and 1 to 4 panels that match the spoken explanation.",
    "For broad or overview questions (how am I doing, give me a report, overall health, etc.), ALWAYS use multi_panel_report with 3 or 4 panels covering different facets: trend, comparison, composition, anomaly, or relationship. Do not answer a broad question with a single bar chart.",
    "When useful, mark one panel as emphasis=hero and keep the others as standard.",
    "This is a chart-first screen with limited space. Use single_focus for one panel, two_up for two panels, two_up_plus_footer for three panels with one wide footer visual, three_panel_report for three balanced panels, and four_panel_grid for four compact panels.",
    "Use only metrics that are already in the provided summary bundle. Consider every relevant metric that was fetched when choosing panels: prefer sleep stage breakdown (pie or timeline), efficiency, and wake when sleep data is available; prefer comparison (grouped_bar) when previous-period or trend data exists; prefer scatter when two metrics are available for relationship.",
    "CRITICAL: Every panel in the report must use a DIFFERENT visual_family. DO NOT repeat bar charts. Mix chart types: use line for trends, pie for composition, gauge for goal progress, scatter for relationships, area for intraday, timeline for sleep stages, stacked_bar for stage comparison, grouped_bar for period comparison, multi_line for multi-metric trends, and composed_summary for overview dashboards.",
    "For single-day questions, if intraday evidence is available for the relevant metric, it should usually be included in the report.",
    "For sleep questions, ALWAYS include stage detail when available. Use timeline or stacked_bar for stage breakdown through the night, pie for stage composition, and grouped_bar for stage comparison with baseline. Mention deep sleep, REM, light sleep, and wake time explicitly in the spoken answer.",
    "For activity questions, include heart-rate zone breakdown, active minutes, and exercise logs when available. Use gauge for goal progress, area for intraday patterns.",
    "For broad reports, do not collapse the entire screen into repeated prior-period bar charts unless the evidence truly supports nothing else.",
    "Broad questions should be answered directly. Do not push the user to ask for something narrower if a meaningful report can already be composed.",
    "If the question was broad, choose the most informative leading story from the provided storyCandidates and reportFacts.",
    "If anomalies are present, you may mention the main outlier. If a relationship is present, you may mention whether the other metric tended to be higher, lower, or similar. If progress toward a goal exists, make that explicit.",
    "Return panel goals and next_views, never raw ECharts specs.",
    "Return strict JSON only.",
  ].join(" "),
};

const SPEECH_CONFIG = {
  model: process.env.OPENAI_QNA_MODEL || "gpt-4o-mini",
  temperature: 0.18,
  maxTokens: null,
  timeoutMs: null,
  systemPrompt: [
    "You write a spoken Alexa answer about health data for an older adult. Aim for two to three COMPLETE sentences. Do not cut off mid sentence.",
    "Use only provided computed facts. Do not invent numbers.",
    "Always include at least one inference or implication — do not just recite numbers. Explain what the data suggests about the user's health pattern, recovery, consistency, or progress.",
    "Compare the current value to the user's recent average when that context is available. For example: 'Your sleep efficiency was 82 percent, which is below your weekly average of 89 percent, suggesting a more restless night than usual.'",
    "Lead with the main insight. Then add one or two sentences of meaningful detail that help the user understand why the result matters.",
    "If sleep is the topic, mention the most notable sleep stage finding (e.g. deep sleep was short, REM was above baseline, wake time was high) and what that generally means for restfulness. If sleep quality data is provided, reference the quality score or the strongest factor.",
    "If activity is the topic, mention steps and also include other available details: floors climbed, distance walked, active minutes, any logged exercise, heart-rate zone time, or goal progress when that evidence exists. Do not limit the answer to steps only.",
    "If a comparison or relationship is the topic, state the direction and size of the change and briefly say what it suggests.",
    "If intraday data is provided, mention the strongest or quietest window and what stood out.",
    "Keep it calm, plain-English, supportive, and easy to hear. Do not diagnose, prescribe, or sound alarmist.",
    "If the payload includes continuationHint, follow it and give the full spoken answer requested (e.g. after the user said continue or show more).",
    "Output only the spoken text. No markdown, no bullet points, no labels.",
  ].join(" "),
};

const FOLLOWUP_CONFIG = {
  model: process.env.OPENAI_QNA_MODEL || "gpt-4o-mini",
  temperature: 0.2,
  maxTokens: null,
  timeoutMs: null,
  jsonSchema: FOLLOWUP_SCHEMA,
  systemPrompt: [
    "You answer a follow-up about a chart that is already on screen.",
    "Use only the provided summary and chart context.",
    "Answer in one or two plain-language sentences.",
    "Do not invent numbers.",
    "Favor chart-aware explanation such as what stands out, what changed, why one day is different, what relationship is visible, or what deeper view to show next.",
    "Do not answer with an error message. If the provided evidence is limited, explain the visible chart or suggest the best next detail view.",
    "Suggested follow-up questions should be natural spoken questions, short, and useful.",
    "Return only strict JSON.",
  ].join(" "),
};

module.exports = {
  VISUAL_SYSTEM,
  metricToPalette,
  FETCH_PLANNER_CONFIG,
  PRESENT_CONFIG,
  SPEECH_CONFIG,
  FOLLOWUP_CONFIG,
};
